// c03-angular/counter/src/app/app.component.ts
import {Component} from '@angular/core';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  value = 0;
  log = '';

  constructor(
    private http: HttpClient
  ) {

  }

  onUpdate(i: number) {
    this.value += i;
  }

  onReset() {
    this.value = 0;
  }

  onSubmit() {
    // alert(`submit value ${this.value}`);
    this.http.post(
      'https://httpbin.org/post',
      {
        value: this.value,
      }
    ).subscribe((res: any) => this.addLog(res.data));
  }

  addLog(s: any) {
    this.log += `\n${new Date()} ${JSON.stringify(s)}`;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div class="text-center">
  <app-counter [value]="value" (update)="onUpdate($event)"></app-counter>
</div>
<div [class.text-center]="true">
  <button (click)="onSubmit()">Submit</button>
  <button (click)="onReset()">Reset</button>
</div>
<div>
  <code>
    <pre>{{ log }}</pre>
  </code>
</div>

// c04-vuejs/counter/src/App.vue
<template>
  <div>
    <div>
      <Counter v-bind:value="value" v-bind:on-update="onUpdate"></Counter>
    </div>
    <div>
      <button v-on:click="onSubmit">Submit</button>
      <button v-on:click="onReset">Reset</button>
    </div>
    <div>
      <code><pre>{{ log }}</pre></code>
    </div>
  </div>
</template>

<script>
import Counter from './components/Counter'
import axios from 'axios'

export default {
  name: 'app',
  data: () => ({
    value: 0,
    log: ''
  }),
  methods: {
    onUpdate (delta) {
      this.value += delta
    },
    onSubmit () {
      // alert(`submit value: ${this.value}`)
      axios.post(
        'https://httpbin.org/post',
        {
          value: this.value
        }
      ).then(response => this.addLog(response.data.data))
    },
    onReset () {
      this.value = 0
    },
    addLog (s) {
      this.log += `\n${new Date()} ${JSON.stringify(s)}`
    }
  },
  components: {
    Counter
  }
}
</script>

<style>

</style>
